package:
  name: hostpurge
  version: 1.2.1

source:
  path: .

build:
  number: 0
  entry_points:
    - hostpurge = hostpurge:main

requirements:
  build:
    - python
  run:
    - python 

